version: '3'
services:
  # database:
  #   image: mysql
  #   container_name: database
  #   restart: unless-stopped
  #   env_file: .env
  #   # environment:
  #   #   - MYSQL_DATABASE=$MYSQL_DB
  #   volumes: 
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=somewordpress
  #     - MYSQL_DATABASE=wordpress
  #     - MYSQL_USER=wordpress
  #     - MYSQL_PASSWORD=wordpress
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   networks:
  #     - app-network
  # wordpress:
  #   depends_on: 
  #     - database
  #   image: wordpress
  #   container_name: wordpress
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - WORDPRESS_DB_HOST=database
  #     - WORDPRESS_DB_USER=wordpress
  #     - WORDPRESS_DB_PASSWORD=wordpress
  #     - WORDPRESS_DB_NAME=wordpress
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - app-network
  # webserver:
  #   depends_on:
  #     - wordpress
  #   image: nginx
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - wordpress:/var/www/html
  #     - ./nginx-conf:/etc/nginx/conf.d
  #     - certbot-etc:/etc/letsencrypt
  #   networks:
  #     - app-network
  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email contact@techlurn.org --agree-tos --no-eff-email --force-renewal -d techlurn.org -d www.techlurn.org

  nexus:
    image: sonatype/docker-nexus3
    # image: sonatype/nexus3 #8GB physical memory required
    container_name: nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
  
volumes:
  certbot-etc:
  wordpress:
  dbdata:
  nexus-data:

networks:
  app-network:
    driver: bridge